# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'config'
gem 'importmap-rails'
gem 'jbuilder'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'redis', '>= 4.0.1'
gem 'sidekiq', '~> 6.2', '>= 6.2.2'
gem 'sprockets-rails'
gem 'turbo-rails'
gem 'responders'
# gem 'kredis'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt', '~> 2.2'
gem 'active_model_serializers', '~> 0.10.12'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]
# gem 'image_processing', '~> 1.2'

group :development, :test do
  gem 'database_cleaner'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-i18n', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'shoulda-matchers'
end

group :development do
  gem 'web-console'
  # gem 'rack-mini-profiler'
  # gem 'spring'
  gem 'annotate'
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
end

group :test do
  gem 'rails-controller-testing'
  gem 'rspec-rails', '~> 6.0.0.rc1'
  gem 'rspec-sidekiq'
  gem 'typhoeus', '~> 1.4'
  gem 'webmock'
end
